# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.CharField(default=' ', max_length=400),
            preserve_default=False,
        ),
    ]
