# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_front_page',
            field=models.BooleanField(default=True),
        ),
    ]
