# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160902_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
