# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Requirements'),
        ),
    ]
