# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
