# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160903_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
